apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-service
  description: Product inventory microservice using Redis with cache-aside pattern
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/dev126712/Backstage/tree/main/docs/product-service
    backstage.io/kubernetes-id: product-micro
    backstage.io/kubernetes-namespace: product-ns
spec:
  type: service
  lifecycle: development
  owner: group:devops
  system: microservice-app
  providesApis:
    - product-service
