apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgres-service
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/dev126712/Backstage/tree/main/docs/postgres-service
    backstage.io/kubernetes-id: postgres-service
spec:
  type: database
  lifecycle: production
  owner: guest
