apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  description: order inventory microservice
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/dev126712/Backstage/tree/main/docs/order-service
spec:
  type: service
  lifecycle: development
  owner: group:devops
  system: ecommerce-platform
  providesApis:
    - product-service
