apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redis-service
  description: redis inventory microservice
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/dev126712/Backstage/tree/main/docs/redis-service
    backstage.io/kubernetes-id: redis-service
spec:
  type: service
  lifecycle: development
  owner: group:devops
  system: microservice-app
  providesApis:
    - redis-service
