name: "Terraform CI"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Quality & Security"
    runs-on: ubuntu-latest
    
    # Required if you're using OIDC for AWS/Azure/GCP credentials
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

# Required for GCP - Use Workload Identity Federation for security
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'project-test-490416'
          # workload_identity_provider: 'projects/1234567/locations/global/workloadIdentityPools/my-pool/providers/my-provider'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 # Specify your version

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform init -backend=false # -backend=false is faster for CI validation

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1' # Fails the build if vulnerabilities are found
          severity: 'CRITICAL,HIGH'

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
