apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev126712fromgit
spec:
  profile:
    displayName: dev126712fromgit
    email: email@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [devops]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Blackbeardfromgit
spec:
  profile:
    displayName: Blackbeardfromgit
    email: email@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [CloudEngineer]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: JeanClaudefromgit
spec:
  profile:
    displayName: Jean Claudefromgit
    email: email1@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [PlatformEngineer]
