apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev126712
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: dev126712
    email: email@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [devops]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Blackbeard
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: Blackbeard
    email: email@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [CloudEngineer]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: JeanClaude
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: Jean Claude
    email: email1@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [PlatformEngineer]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: BruceWayne
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: Bruce Wayne
    email: email@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [Developper]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Luffy
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: Luffy
    email: email@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [PlatformEngineer]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Torreto
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: Torreto
    email: email@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [Administrator]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Zoro
  annotations:
    backstage.io/techdocs-ref: value
spec:
  profile:
    displayName: Zoro
    email: email@example.cpm
    picture: https://github.com/dev126712.png
  memberOf: [Juniordevelopper]
