apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: serverless-demo
  title: Serverless 3 Tier Application GCP
  description: Serverless 3 tier Application on gcp with Cloud Run V2 for Frontend & Backend and Cloud SQL (PostgreSQL 15) for Database
spec:
  owner: group:Developper
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: Project Settings
      properties:
        gcp_project_id:
          title: GCP Project ID
          type: string
          description: The ID of the project to deploy to.
    - title: Deployment Location
      required:
        - cloud_run_region
      properties:
        cloud_run_region:
          title: Cloud Run Region
          type: string
          description: Which GCP region should this service be deployed to?
          # This creates the multiple-choice dropdown
          enum:
            - us-central1
            - europe-west1
            - asia-east1
          enumNames:
            - "Iowa (us-central1)"
            - "Belgium (europe-west1)"
            - "Taiwan (asia-east1)"
          default: us-central1
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./base
        values:
          name: ${{ parameters.name }}
          repoUrl: ${{ parameters.repoUrl }} 

    - id: fetchModule
      name: Fetch CI main.tf module
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/dev126712/Backstage/blob/main/template/serverless-3-tier-gcp/skeleton



    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/info-catalog.yml'
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
