apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: serverless-demo
  title: Serverless 3 Tier Application GCP
  description: Serverless 3 tier Application on gcp with Cloud Run V2 for Frontend & Backend and Cloud SQL (PostgreSQL 15) for Database
spec:
  owner: group:Developper
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:

  
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5

            
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

              
    - title: Project Settings
      properties:
      
        vpc:
          title: VPC
          type: string
          description: VPC Name
       
        subnet:
          title: subnet
          type: string
          description: Subnet Name
        
        project_id:
          title: GCP Project ID
          type: string
          description: The ID of the project to deploy to.
        
        cloud_run_region:
          title: Cloud Run Region
          type: string
          description: Which GCP region should this service be deployed to?
          enum:
            - us-central1
            - europe-west1
            - asia-east1
          enumNames:
            - "Iowa (us-central1)"
            - "Belgium (europe-west1)"
            - "Taiwan (asia-east1)"
          default: us-central1
        
        google_cloud_run_service_name:
          title: Google Cloud Service Name
          type: string
          description: Cloud Run Service Name
        
        frontend_container_image:
          title: Frontend Image
          type: string
          description: The container frontend image
          default:
        
        backend_container_image:
          title: Backend Image
          type: string
          description: The container frontend image
          default:
        
        database_name:
          title: Database Name
          type: string
          description: The Database Name ( Default: app-db-instance )
          default: app-db-instance
        
        database_version:
          title: Database Version
          type: string
          description: The Database Version ( Default: POSTGRES_15 )
          enum:
            - POSTGRES_15
            - POSTGRES_14
            - MYSQL_8_0
          default: POSTGRES_15
        
        database_tier:
          title: Database Tier
          type: string
          description: The Database Version ( Default: db-f1-micro )
          enum:
            - db-f1-micro
            - db-g1-small
            - db-custom-1-3840
          default: db-f1-micro

          
  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./base
        values:
          name: ${{ parameters.name }}
          repoUrl: ${{ parameters.repoUrl }} 

    - id: fetchModule
      name: Fetch CI main.tf module
      action: fetch:template
      input:
        targetPath: ./
        url: https://github.com/dev126712/Backstage/blob/main/template/serverless-3-tier-gcp/skeleton
        values:
          name: ${{ parameters.name }}
          vpc: ${{ parameters.vpc }}
          subnet: ${{ parameters.subnet }}
          project_id: ${{ parameters.project_id }}
          cloud_run_region: ${{ parameters.cloud_run_region }}
          google_cloud_run_service_name: ${{ parameters.google_cloud_run_service_name }}
          frontend_container_image: ${{ parameters.frontend_container_image }}
          backend_container_image: ${{ parameters.backend_container_image }}
          database_name: ${{ parameters.database_name }}
          database_version: ${{ parameters.database_version }}
          database_tier: ${{ parameters.database_tier }}


    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/info-catalog.yml'
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
